# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ventana_coincidencias.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ventana_Coincidencias(object):
    def setupUi(self, Ventana_Coincidencias):
        Ventana_Coincidencias.setObjectName("Ventana_Coincidencias")
        Ventana_Coincidencias.resize(474, 328)
        self.verticalLayout = QtWidgets.QVBoxLayout(Ventana_Coincidencias)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Ventana_Coincidencias)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.ListaCoincidencias = QtWidgets.QListWidget(Ventana_Coincidencias)
        self.ListaCoincidencias.setObjectName("ListaCoincidencias")
        self.verticalLayout.addWidget(self.ListaCoincidencias)
        self.buttonBox = QtWidgets.QDialogButtonBox(Ventana_Coincidencias)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Ventana_Coincidencias)
        self.buttonBox.accepted.connect(Ventana_Coincidencias.accept)
        self.buttonBox.rejected.connect(Ventana_Coincidencias.reject)
        QtCore.QMetaObject.connectSlotsByName(Ventana_Coincidencias)

    def retranslateUi(self, Ventana_Coincidencias):
        _translate = QtCore.QCoreApplication.translate
        Ventana_Coincidencias.setWindowTitle(_translate("Ventana_Coincidencias", "Elige la opción requerida"))
        self.label.setText(_translate("Ventana_Coincidencias", "<html><head/><body><p>Se encontraron las siguientes coincidencias:</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ventana_Coincidencias = QtWidgets.QDialog()
    ui = Ui_Ventana_Coincidencias()
    ui.setupUi(Ventana_Coincidencias)
    Ventana_Coincidencias.show()
    sys.exit(app.exec_())
