# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ventana_alerta.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaAlerta(object):
    def setupUi(self, VentanaAlerta):
        VentanaAlerta.setObjectName("VentanaAlerta")
        VentanaAlerta.resize(337, 172)
        VentanaAlerta.setMinimumSize(QtCore.QSize(337, 172))
        VentanaAlerta.setMaximumSize(QtCore.QSize(337, 172))
        self.verticalLayout = QtWidgets.QVBoxLayout(VentanaAlerta)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MensajeNoHay = QtWidgets.QLabel(VentanaAlerta)
        self.MensajeNoHay.setObjectName("MensajeNoHay")
        self.verticalLayout.addWidget(self.MensajeNoHay)
        self.buttonBox = QtWidgets.QDialogButtonBox(VentanaAlerta)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(VentanaAlerta)
        self.buttonBox.accepted.connect(VentanaAlerta.accept)
        self.buttonBox.rejected.connect(VentanaAlerta.reject)
        QtCore.QMetaObject.connectSlotsByName(VentanaAlerta)

    def retranslateUi(self, VentanaAlerta):
        _translate = QtCore.QCoreApplication.translate
        VentanaAlerta.setWindowTitle(_translate("VentanaAlerta", "Dialog"))
        self.MensajeNoHay.setText(_translate("VentanaAlerta", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">No hay resultados</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaAlerta = QtWidgets.QDialog()
    ui = Ui_VentanaAlerta()
    ui.setupUi(VentanaAlerta)
    VentanaAlerta.show()
    sys.exit(app.exec_())
