# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ventana_madre.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(862, 616)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.TabBuscar = QtWidgets.QWidget()
        self.TabBuscar.setObjectName("TabBuscar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.TabBuscar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.TabBuscar)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CuadroBuscar = QtWidgets.QLineEdit(self.widget)
        self.CuadroBuscar.setObjectName("CuadroBuscar")
        self.horizontalLayout.addWidget(self.CuadroBuscar)
        self.BotonBuscar = QtWidgets.QPushButton(self.widget)
        self.BotonBuscar.setObjectName("BotonBuscar")
        self.horizontalLayout.addWidget(self.BotonBuscar)
        self.BotonAgregar = QtWidgets.QPushButton(self.widget)
        self.BotonAgregar.setObjectName("BotonAgregar")
        self.horizontalLayout.addWidget(self.BotonAgregar)
        self.verticalLayout.addWidget(self.widget)
        self.Mensajes2Usuario = QtWidgets.QLabel(self.TabBuscar)
        self.Mensajes2Usuario.setObjectName("Mensajes2Usuario")
        self.verticalLayout.addWidget(self.Mensajes2Usuario)
        self.frame_2 = QtWidgets.QFrame(self.TabBuscar)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Mostrar = QtWidgets.QListWidget(self.frame_2)
        self.Mostrar.setObjectName("Mostrar")
        self.horizontalLayout_2.addWidget(self.Mostrar)
        self.widget_2 = QtWidgets.QWidget(self.frame_2)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.BotonEditar = QtWidgets.QPushButton(self.widget_2)
        self.BotonEditar.setObjectName("BotonEditar")
        self.gridLayout_2.addWidget(self.BotonEditar, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 5, 0, 1, 1)
        self.AbrirPDF = QtWidgets.QPushButton(self.widget_2)
        self.AbrirPDF.setObjectName("AbrirPDF")
        self.gridLayout_2.addWidget(self.AbrirPDF, 4, 0, 1, 1)
        self.BotonEliminar = QtWidgets.QPushButton(self.widget_2)
        self.BotonEliminar.setObjectName("BotonEliminar")
        self.gridLayout_2.addWidget(self.BotonEliminar, 6, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        self.buttonActualizarInfo = QtWidgets.QPushButton(self.widget_2)
        self.buttonActualizarInfo.setObjectName("buttonActualizarInfo")
        self.gridLayout_2.addWidget(self.buttonActualizarInfo, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.frame_2)
        self.tabWidget.addTab(self.TabBuscar, "")
        self.tabListas = QtWidgets.QWidget()
        self.tabListas.setObjectName("tabListas")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabListas)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Mensajes2UsuarioTabListas = QtWidgets.QLabel(self.tabListas)
        self.Mensajes2UsuarioTabListas.setObjectName("Mensajes2UsuarioTabListas")
        self.verticalLayout_2.addWidget(self.Mensajes2UsuarioTabListas)
        self.frame = QtWidgets.QFrame(self.tabListas)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_3 = QtWidgets.QWidget(self.frame)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_3.setStyleSheet("#widget_3\n"
"{\n"
"    width : 30%\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ArbolListas = QtWidgets.QTreeWidget(self.widget_3)
        self.ArbolListas.setObjectName("ArbolListas")
        self.ArbolListas.header().setVisible(False)
        self.gridLayout_4.addWidget(self.ArbolListas, 11, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.buttonActualizarArbol = QtWidgets.QPushButton(self.widget_3)
        self.buttonActualizarArbol.setObjectName("buttonActualizarArbol")
        self.horizontalLayout_4.addWidget(self.buttonActualizarArbol)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 6, 0, 3, 1)
        self.horizontalLayout_3.addWidget(self.widget_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.MostrarListas = QtWidgets.QListWidget(self.frame)
        self.MostrarListas.setStyleSheet("")
        self.MostrarListas.setObjectName("MostrarListas")
        self.verticalLayout_4.addWidget(self.MostrarListas)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.buttonGuardarCSV = QtWidgets.QPushButton(self.frame)
        self.buttonGuardarCSV.setObjectName("buttonGuardarCSV")
        self.horizontalLayout_5.addWidget(self.buttonGuardarCSV)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.buttonEliminarTabListas = QtWidgets.QPushButton(self.frame)
        self.buttonEliminarTabListas.setObjectName("buttonEliminarTabListas")
        self.horizontalLayout_5.addWidget(self.buttonEliminarTabListas)
        self.buttonAgregarTabListas = QtWidgets.QPushButton(self.frame)
        self.buttonAgregarTabListas.setObjectName("buttonAgregarTabListas")
        self.horizontalLayout_5.addWidget(self.buttonAgregarTabListas)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 2)
        self.verticalLayout_2.addWidget(self.frame)
        self.tabWidget.addTab(self.tabListas, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 862, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuasdasd = QtWidgets.QMenu(self.menuBar)
        self.menuasdasd.setObjectName("menuasdasd")
        self.menuJSON = QtWidgets.QMenu(self.menuasdasd)
        self.menuJSON.setObjectName("menuJSON")
        self.menuBase_de_datos = QtWidgets.QMenu(self.menuasdasd)
        self.menuBase_de_datos.setObjectName("menuBase_de_datos")
        self.menuCursos = QtWidgets.QMenu(self.menuBar)
        self.menuCursos.setObjectName("menuCursos")
        MainWindow.setMenuBar(self.menuBar)
        self.actionImportar = QtWidgets.QAction(MainWindow)
        self.actionImportar.setObjectName("actionImportar")
        self.actionExportar = QtWidgets.QAction(MainWindow)
        self.actionExportar.setObjectName("actionExportar")
        self.actionGenerar_lista = QtWidgets.QAction(MainWindow)
        self.actionGenerar_lista.setObjectName("actionGenerar_lista")
        self.actionOrganizar_PDFs = QtWidgets.QAction(MainWindow)
        self.actionOrganizar_PDFs.setObjectName("actionOrganizar_PDFs")
        self.actionImportar_JSON = QtWidgets.QAction(MainWindow)
        self.actionImportar_JSON.setObjectName("actionImportar_JSON")
        self.actionExportar_JSON = QtWidgets.QAction(MainWindow)
        self.actionExportar_JSON.setObjectName("actionExportar_JSON")
        self.actionEditar_directorios = QtWidgets.QAction(MainWindow)
        self.actionEditar_directorios.setObjectName("actionEditar_directorios")
        self.actionEscanear_PDF = QtWidgets.QAction(MainWindow)
        self.actionEscanear_PDF.setObjectName("actionEscanear_PDF")
        self.actionConfrimar_admisi_n = QtWidgets.QAction(MainWindow)
        self.actionConfrimar_admisi_n.setObjectName("actionConfrimar_admisi_n")
        self.actionConfirmar_admision = QtWidgets.QAction(MainWindow)
        self.actionConfirmar_admision.setObjectName("actionConfirmar_admision")
        self.actionImportacion_masiva = QtWidgets.QAction(MainWindow)
        self.actionImportacion_masiva.setObjectName("actionImportacion_masiva")
        self.menuJSON.addAction(self.actionImportar_JSON)
        self.menuJSON.addAction(self.actionExportar_JSON)
        self.menuBase_de_datos.addAction(self.actionExportar)
        self.menuBase_de_datos.addSeparator()
        self.menuBase_de_datos.addAction(self.actionImportar)
        self.menuasdasd.addAction(self.menuBase_de_datos.menuAction())
        self.menuasdasd.addAction(self.actionGenerar_lista)
        self.menuasdasd.addAction(self.menuJSON.menuAction())
        self.menuasdasd.addAction(self.actionImportacion_masiva)
        self.menuCursos.addAction(self.actionOrganizar_PDFs)
        self.menuCursos.addAction(self.actionEscanear_PDF)
        self.menuCursos.addSeparator()
        self.menuCursos.addAction(self.actionEditar_directorios)
        self.menuCursos.addSeparator()
        self.menuCursos.addAction(self.actionConfirmar_admision)
        self.menuBar.addAction(self.menuasdasd.menuAction())
        self.menuBar.addAction(self.menuCursos.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gestor de cursos"))
        self.TabBuscar.setToolTip(_translate("MainWindow", "<html><head/><body><p>Busca alumnos por nombre</p></body></html>"))
        self.BotonBuscar.setText(_translate("MainWindow", "Buscar"))
        self.BotonAgregar.setText(_translate("MainWindow", "Agregar nuevo"))
        self.Mensajes2Usuario.setText(_translate("MainWindow", "Mensajes al usuario"))
        self.BotonEditar.setText(_translate("MainWindow", "Editar"))
        self.AbrirPDF.setText(_translate("MainWindow", "Abrir PDF"))
        self.BotonEliminar.setText(_translate("MainWindow", "Eliminar"))
        self.buttonActualizarInfo.setText(_translate("MainWindow", "Actualizar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabBuscar), _translate("MainWindow", "Buscar", "En serio"))
        self.tabListas.setToolTip(_translate("MainWindow", "<html><head/><body><p>Administra tus cursos por salon</p></body></html>"))
        self.Mensajes2UsuarioTabListas.setText(_translate("MainWindow", "<html><head/><body><p>Mensajes para el usuario</p></body></html>"))
        self.ArbolListas.setToolTip(_translate("MainWindow", "<html><head/><body><p>Árbol de cursos</p></body></html>"))
        self.ArbolListas.headerItem().setText(0, _translate("MainWindow", "Cursos por salon"))
        self.buttonActualizarArbol.setToolTip(_translate("MainWindow", "<html><head/><body><p>Carga o actualiza el árbol de cursos</p></body></html>"))
        self.buttonActualizarArbol.setText(_translate("MainWindow", "Cargar"))
        self.MostrarListas.setToolTip(_translate("MainWindow", "<html><head/><body><p>Aquí se muestra la lista del salon</p></body></html>"))
        self.buttonGuardarCSV.setToolTip(_translate("MainWindow", "<html><head/><body><p>Guarda salon a un archivo CSV o JSON</p></body></html>"))
        self.buttonGuardarCSV.setText(_translate("MainWindow", "Guardar archivo"))
        self.buttonEliminarTabListas.setToolTip(_translate("MainWindow", "<html><head/><body><p>Elimina el elemento seleccionado</p></body></html>"))
        self.buttonEliminarTabListas.setText(_translate("MainWindow", "Eliminar"))
        self.buttonAgregarTabListas.setToolTip(_translate("MainWindow", "<html><head/><body><p>Agrega un alumno a este salon</p></body></html>"))
        self.buttonAgregarTabListas.setText(_translate("MainWindow", "Agregar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabListas), _translate("MainWindow", "Listas"))
        self.menuasdasd.setTitle(_translate("MainWindow", "Archivos"))
        self.menuJSON.setTitle(_translate("MainWindow", "JSON"))
        self.menuBase_de_datos.setTitle(_translate("MainWindow", "Base de datos"))
        self.menuCursos.setTitle(_translate("MainWindow", "Cursos"))
        self.actionImportar.setText(_translate("MainWindow", "Cargar base de datos"))
        self.actionExportar.setText(_translate("MainWindow", "Actualizar base de datos"))
        self.actionGenerar_lista.setText(_translate("MainWindow", "Generar lista"))
        self.actionOrganizar_PDFs.setText(_translate("MainWindow", "Organizar PDFs"))
        self.actionImportar_JSON.setText(_translate("MainWindow", "Cargar JSON"))
        self.actionExportar_JSON.setText(_translate("MainWindow", "Generar JSON"))
        self.actionEditar_directorios.setText(_translate("MainWindow", "Editar directorios"))
        self.actionEscanear_PDF.setText(_translate("MainWindow", "Escanear PDFs"))
        self.actionConfrimar_admisi_n.setText(_translate("MainWindow", "Confrimar admisión"))
        self.actionConfirmar_admision.setText(_translate("MainWindow", "Confirmar admisión"))
        self.actionImportacion_masiva.setText(_translate("MainWindow", "Importación masiva"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
