# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ventana_cerrar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaCerrar(object):
    def setupUi(self, VentanaCerrar):
        VentanaCerrar.setObjectName("VentanaCerrar")
        VentanaCerrar.resize(530, 398)
        VentanaCerrar.setMinimumSize(QtCore.QSize(530, 398))
        VentanaCerrar.setMaximumSize(QtCore.QSize(530, 398))
        self.verticalLayout = QtWidgets.QVBoxLayout(VentanaCerrar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(VentanaCerrar)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.scrollArea = QtWidgets.QScrollArea(VentanaCerrar)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 510, 276))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.MostrarContenido = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.MostrarContenido.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.MostrarContenido.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.MostrarContenido.setObjectName("MostrarContenido")
        self.gridLayout.addWidget(self.MostrarContenido, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.widget_2 = QtWidgets.QWidget(VentanaCerrar)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NoCerrar = QtWidgets.QPushButton(self.widget_2)
        self.NoCerrar.setObjectName("NoCerrar")
        self.horizontalLayout.addWidget(self.NoCerrar)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget_2)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(VentanaCerrar)
        self.buttonBox.accepted.connect(VentanaCerrar.accept)
        self.buttonBox.rejected.connect(VentanaCerrar.reject)
        QtCore.QMetaObject.connectSlotsByName(VentanaCerrar)

    def retranslateUi(self, VentanaCerrar):
        _translate = QtCore.QCoreApplication.translate
        VentanaCerrar.setWindowTitle(_translate("VentanaCerrar", "Hay cambios sin guardar"))
        self.label.setText(_translate("VentanaCerrar", "<html><head/><body><p>Al parecer hay cambios sin guardar.</p><p> ¿Deseas guardar los cambios a la base de datos?</p></body></html>"))
        self.MostrarContenido.setText(_translate("VentanaCerrar", "TextLabel"))
        self.NoCerrar.setText(_translate("VentanaCerrar", "No cerrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaCerrar = QtWidgets.QDialog()
    ui = Ui_VentanaCerrar()
    ui.setupUi(VentanaCerrar)
    VentanaCerrar.show()
    sys.exit(app.exec_())
