# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ventana_editar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaEditar(object):
    def setupUi(self, VentanaEditar):
        VentanaEditar.setObjectName("VentanaEditar")
        VentanaEditar.resize(525, 120)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VentanaEditar.sizePolicy().hasHeightForWidth())
        VentanaEditar.setSizePolicy(sizePolicy)
        VentanaEditar.setMinimumSize(QtCore.QSize(525, 120))
        VentanaEditar.setMaximumSize(QtCore.QSize(525, 120))
        self.verticalLayout = QtWidgets.QVBoxLayout(VentanaEditar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.NombreAlumno = QtWidgets.QLabel(VentanaEditar)
        self.NombreAlumno.setObjectName("NombreAlumno")
        self.verticalLayout.addWidget(self.NombreAlumno)
        self.widget = QtWidgets.QWidget(VentanaEditar)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AtributoEditar = QtWidgets.QLabel(self.widget)
        self.AtributoEditar.setObjectName("AtributoEditar")
        self.horizontalLayout.addWidget(self.AtributoEditar)
        self.EntradaEditar = QtWidgets.QLineEdit(self.widget)
        self.EntradaEditar.setObjectName("EntradaEditar")
        self.horizontalLayout.addWidget(self.EntradaEditar)
        self.verticalLayout.addWidget(self.widget)
        self.buttonBox = QtWidgets.QDialogButtonBox(VentanaEditar)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.AtributoEditar.setBuddy(self.EntradaEditar)

        self.retranslateUi(VentanaEditar)
        self.buttonBox.accepted.connect(VentanaEditar.accept)
        self.buttonBox.rejected.connect(VentanaEditar.reject)
        QtCore.QMetaObject.connectSlotsByName(VentanaEditar)

    def retranslateUi(self, VentanaEditar):
        _translate = QtCore.QCoreApplication.translate
        VentanaEditar.setWindowTitle(_translate("VentanaEditar", "Editar"))
        self.NombreAlumno.setText(_translate("VentanaEditar", "Nombre del alumno"))
        self.AtributoEditar.setText(_translate("VentanaEditar", "Atributo: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaEditar = QtWidgets.QDialog()
    ui = Ui_VentanaEditar()
    ui.setupUi(VentanaEditar)
    VentanaEditar.show()
    sys.exit(app.exec_())
